sudo: false
language: python
python:
    - '2.7'

install:
    - pip install coveralls
    - pip install -r requirements.txt

script:
    - make clean
    - make -B test
    - coverage run --source=src test/python/test_simple_io.py
    
after_success:
  coveralls
